---
# 连接初始化信息
robot_mac:
  &robot_mac DE:F2:A5:62:54:A1
host_mac:
  &host_mac A0:A4:C5:2E:EF:37
server_ip:
  &server_ip 192.168.10.2
reg_client_message:
  {"message_type": "register_client","client_type": 3,"mac_address": *host_mac }

# 订阅状态信息
set_sensor_data_info: # 设置传感器实时参数
  {"message_type": "set_sensor_data_info","client_type": 3,"mac_address": *host_mac}
get_all_robot_info_message: # 获取服务器上所有机器人信息
  {"message_type": "get_all_robot_info","client_type": 3,"mac_address": *host_mac}
report_loc_status: # 定位状态
  {"message_type": 'report_loc_status',"client_type": 3,"mac_address": *host_mac}
move_status: # 移动状态 v2
  {"message_type": 'report_move_status_v2',"client_type": 3,"mac_address": *host_mac}
move_status1: # 移动状态 v1
  {"message_type": 'report_move_status',"client_type": 3,"mac_address": *host_mac}
report_button_status: # 按键状态
  {"message_type": 'report_button_status',"client_type": 3,"mac_address": *host_mac}
report_charge_status: # 充电状态
  { "mac_address": *host_mac, "ip_address": "192.168.10.3", "name": "robot1", "id": 1, "message_type": "report_charge_status", "charge_status": 0 }
report_poi_status: # 上报位置信息
  {"message_type": 'report_poi_status',"client_type": 3,"mac_address": *host_mac}
get_file: # 获取点位信息
  {"message_type": "get_file","file_name": "poi.json"}
update_file: # 更新点位信息
  {"message_type": "update_file", "file_name": "poi.json", "md5": "70b428bb6ac7af8ce7f88fe139bccd44", "content": "eyJ2ZXJzaW9uIjogIjEuMC4wIiwgImVuY29kaW5nIjogInV0Zi04IiwgInBvaV9pbmZvIjogW3sibmFtZSI6ICJwMSIsICJwb3NpdGlvbiI6IHsieCI6IC0yMS41NCwgInkiOiA5LjQ3LCAieWF3IjogMC4wMn19LCB7Im5hbWUiOiAicDIiLCAicG9zaXRpb24iOiB7IngiOiAtMjEuMzMsICJ5IjogNy43MywgInlhdyI6IDUuOTN9fSwgeyJuYW1lIjogInAzIiwgInBvc2l0aW9uIjogeyJ4IjogLTIxLjM4LCAieSI6IDYuNDgsICJ5YXciOiA2LjE2fX0sIHsibmFtZSI6ICJwNCIsICJwb3NpdGlvbiI6IHsieCI6IC0xNi4yMiwgInkiOiA1LjIsICJ5YXciOiAwLjA2fX0sIHsibmFtZSI6ICJwNSIsICJwb3NpdGlvbiI6IHsieCI6IC0xMi42MywgInkiOiA1LjE1LCAieWF3IjogNi4yN319LCB7Im5hbWUiOiAicDYiLCAicG9zaXRpb24iOiB7IngiOiAtOS4zMywgInkiOiA1LjIsICJ5YXciOiAwLjA1fX0sIHsibmFtZSI6ICJ3b3JrIiwgInBvc2l0aW9uIjogeyJ4IjogLTAuNTgsICJ5IjogNS4xNywgInlhdyI6IDAuMDl9fSwgeyJuYW1lIjogInA3IiwgInBvc2l0aW9uIjogeyJ4IjogLTYuMjksICJ5IjogNS4wNywgInlhdyI6IDYuMjd9fSwgeyJuYW1lIjogInA4IiwgInBvc2l0aW9uIjogeyJ4IjogLTMuMTgsICJ5IjogNS4wLCAieWF3IjogMC4yMn19LCB7Im5hbWUiOiAiY2FyNiIsICJwb3NpdGlvbiI6IHsieCI6IC0yMS4zMiwgInkiOiA4Ljg1LCAieWF3IjogNi4yMX19LCB7Im5hbWUiOiAiY2FyNCIsICJwb3NpdGlvbiI6IHsieCI6IC0xOC4yMywgInkiOiA1LjIzLCAieWF3IjogMy4xMX19LCB7Im5hbWUiOiAiaG9tZSIsICJwb3NpdGlvbiI6IHsieCI6IC05LjYxLCAieSI6IDEwLjQ2LCAieWF3IjogMC4wNX19LCB7Im5hbWUiOiAiY2FyNSIsICJwb3NpdGlvbiI6IHsieCI6IC0yMS4zOSwgInkiOiA3LjAyLCAieWF3IjogNi4xOX19LCB7Im5hbWUiOiAiY2FyMiIsICJwb3NpdGlvbiI6IHsieCI6IC0xMS40LCAieSI6IDUuMjksICJ5YXciOiAzLjI0fX0sIHsibmFtZSI6ICJjYXIzIiwgInBvc2l0aW9uIjogeyJ4IjogLTE0LjQ1LCAieSI6IDUuMTUsICJ5YXciOiAzLjAzfX0sIHsibmFtZSI6ICJjYXIxIiwgInBvc2l0aW9uIjogeyJ4IjogLTguMDYsICJ5IjogNS4yNSwgInlhdyI6IDMuMn19XSwgImNoYXJnZV9wb2ludHNfaW5mbyI6IFt7Im5hbWUiOiAiY2hhcmdlIiwgInBvc2l0aW9uIjogeyJ4IjogLTEyLjcyNTcsICJ5IjogOS4xMDYzLCAieWF3IjogMC4wMzc1NDUxfX1dLCAiZ3JvdXBzIjogeyIjdGVzdGluZyMiOiBbInAxIiwgInAyIiwgInAzIiwgInA0IiwgInA1IiwgInA2IiwgInA3IiwgInA4IiwgIndvcmsiLCAiaG9tZSIsICJjYXIxIiwgImNhcjIiLCAiY2FyMyIsICJjYXI0IiwgImNhcjUiLCAiY2FyNiJdfX0=","destination": "both","file_size": 1376,"version": 0 }
apply_map: # 切换地图
  {"message_type": "apply_map","map_name": "HongQiao"}

# 控制机器人
poi_action1: # 导航到常用位置（poi_action/goto）
  { "message_type": "poi_action", "robot_mac_address": *robot_mac, "mode": "goto", "params": { "name": "p1" } }
move: # 移动一段距离
  { "message_type": "move", "robot_mac_address": *robot_mac, "vx": 0.5, "vy": 0, "vtheta": 0, }
# 取消导航
cancel_goal:
  { "message_type": "cancel_goal", "robot_mac_address": *robot_mac,}
charge: # 自动充电
  { "message_type": "charge", "robot_mac_address":  *robot_mac,}
goCharge: # 导航到对位点并自动充电
  { "message_type": "charge", "robot_mac_address": *robot_mac, "charge_point_name": "charge" }
cancel_charge: # 取消充电
  { "message_type": "cancel_charge", "robot_mac_address": *robot_mac, }
power_off: # 关机
  { "message_type": "shutdown", "robot_mac_address": *robot_mac,"poweroff_delay": 30, "auto_poweron_delay": 60, "auto_poweron_time": "9:30:00" }
...